import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LanguageProvider } from "../context/LanguageContext";
import LanguageSelector from "../components/LanguageSelector";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: "/manifest.json",
  themeColor: "#020617",
};

export default function RootLayout({ children }) {
 return (
  <html lang="en">
    <body className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
  <LanguageProvider>
    {children}

    <div className="fixed bottom-20 right-4 z-50">
      <LanguageSelector />
    </div>
  </LanguageProvider>
</body>
  </html>
);
}
